version: 2.1

refs:
  - &only_master
    filters:
      branches:
        only: master

orbs:
  node: circleci/node@5.2.0

jobs:
  release_package:
    executor: node/default
    steps:
      - checkout
      - run:
          name: NPM Authentication
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn semantic-release
          name: Release

workflows:
  release:
    jobs:
      - release_package:
          <<: *only_master
          context:
            - common-env-vars
