version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  release:
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn semantic-release
          name: Release

workflows:
  release:
    jobs:
      - release
